### ISSUE TITLE
Image captions are missing a word

### ISSUE THREAD

**Issue by AdamZ** [susanemcg/DigitalSecurityForJournalists#6]
Also in 3.1, the last two images in the chapter have captions that read

> An connection leaves all the contents of your packets visible to anyone on the network.

and

> An connection, meanwhile, protects the contents. Only the metadata remains visible.

They should presumably be "an http connection", and "an https connection".

**Comment by susanemcg** [comment]
Ah, thanks. Was missing a tag in my LaTeX to markdown converter. Though oddly it then also stopped auto-producing captions, but that's for next time!
