### ISSUE TITLE
Footnote links all cause 404

### ISSUE THREAD

**Issue by AdamZ** [susanemcg/DigitalSecurityForJournalists#7]
All of the footnote links in the book appear to be like the following:

> `<sup>[47](footnotes/README.html#fn47)</sup>`

The links all cause a 404 error, because they are all relative to the current folder. They should look like `<sup>[47](../footnotes/README.html#fn47)</sup>` (the ones in the introduction work fine, because it is the same folder as the footnotes folder). The "self" links at the end of each footnote also cause 404s, for the same reason.

Also, the anchors within the footnote page don't work. The anchor name (e.g., `fnref47`) should be the `id` attribute of a tag. That way the browser will jump to the correct position on the page.

**Comment by susanemcg** [comment]
Unfortunately, GitBook doesn't correctly support anchors yet; the hashes had been generated by a previous conversion step, so in the rush of first publishing I just left them there. After an embarrassing number of attempts, however, the footnotes do now at least direct to the footnotes page. Both anchors and "self" links have been eliminated by my [hyper-documented conversion process.](https://github.com/susanemcg/pandoc-tufteLaTeX2GitBook)
